USE [master]
GO

--https://www.sqlskills.com/blogs/erin/query-store-settings/
--SQL Server 2016 & 2017
ALTER DATABASE [ChicagoBulls] SET QUERY_STORE = ON;
GO

ALTER DATABASE [ChicagoBulls] 
SET QUERY_STORE (OPERATION_MODE = READ_WRITE,
				QUERY_CAPTURE_MODE = AUTO, 
				MAX_PLANS_PER_QUERY = 200,
				MAX_STORAGE_SIZE_MB = 128, 
				CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
				SIZE_BASED_CLEANUP_MODE = AUTO,
				DATA_FLUSH_INTERVAL_SECONDS = 900,
				INTERVAL_LENGTH_MINUTES = 60
				);
GO
