-- find if column has default value set
SELECT	DC.*
FROM	SYS.COLUMNS AS C (NOLOCK)
	INNER JOIN SYS.DEFAULT_CONSTRAINTS AS DC (NOLOCK)
		ON C.OBJECT_ID = DC.PARENT_OBJECT_ID
		AND	C.COLUMN_ID = DC.PARENT_COLUMN_ID
WHERE	OBJECT_NAME(C.OBJECT_ID) = 'LEADS' -- REPLACE TABLE NAME
AND		C.Name = 'LeadManagementLeadTime'  -- REPLACE COLUMN NAME
AND		Type_Desc = 'DEFAULT_CONSTRAINT'

