
-- Find the date of the Week day
SELECT	CONVERT(VARCHAR(10), DATEADD(D, -1 * DATEPART(WEEKDAY, GETDATE()), GETDATE()) + 1, 101) AS SundayWeekDay,
		CONVERT(VARCHAR(10), CASE WHEN DATEPART(WEEKDAY, GETDATE()) = 2 THEN GETDATE() ELSE GETDATE()-DATEPART(WEEKDAY, GETDATE()-2) END, 101) AS MondayWeekDay