
SELECT	DB_NAME(DB_ID()) AS DatabaseName,
		S.NAME AS SchemaName,
		T.NAME AS TableName,
		C.NAME AS ColumnName,
		C.MAX_LENGTH as MaxLength
FROM	SYS.TABLES AS T
	INNER JOIN SYS.SCHEMAS AS S
		ON T.SCHEMA_ID = S.SCHEMA_ID
	INNER JOIN SYS.COLUMNS AS C
		ON C.OBJECT_ID = T.OBJECT_ID
WHERE	C.MAX_LENGTH >= 1000
AND		C.OBJECT_ID > 100
ORDER BY S.NAME, T.NAME
