-- Find Index Insert, Update, Delete Count
SELECT 
	  OBJECT_SCHEMA_NAME(A.[OBJECT_ID]) AS 'SchemaName'
	, OBJECT_NAME(A.[OBJECT_ID]) AS [OBJECT NAME], 
       I.[NAME] AS [INDEX NAME], 
       A.LEAF_INSERT_COUNT, 
       A.LEAF_UPDATE_COUNT, 
       A.LEAF_DELETE_COUNT 
FROM   SYS.DM_DB_INDEX_OPERATIONAL_STATS (NULL,NULL,NULL,NULL ) A 
       INNER JOIN SYS.INDEXES AS I 
         ON I.[OBJECT_ID] = A.[OBJECT_ID] 
            AND I.INDEX_ID = A.INDEX_ID 
WHERE  OBJECTPROPERTY(A.[OBJECT_ID],'IsUserTable') = 1
--AND		OBJECT_NAME(A.[OBJECT_ID]) = 'BILLABLELEADS'
ORDER BY        
	A.LEAF_INSERT_COUNT DESC, 
	A.LEAF_UPDATE_COUNT DESC, 
	A.LEAF_DELETE_COUNT DESC