SELECT ISNUMERIC('$') AS [What]
	UNION ALL
	SELECT ISNUMERIC('£') AS [What]
	UNION ALL
	SELECT ISNUMERIC(',') AS [What]
	UNION ALL
	SELECT ISNUMERIC('.') AS [What]
	UNION ALL
	SELECT ISNUMERIC('0e+99') AS [What]
	UNION ALL
	SELECT ISNUMERIC('2e2') AS [What]
	UNION ALL
	SELECT ISNUMERIC('12D4') AS [What]
	UNION ALL
	SELECT ISNUMERIC(',1,1,1,1,1,1,1') AS [What]
	UNION ALL
	SELECT ISNUMERIC('-') AS [What]
	UNION ALL
	SELECT ISNUMERIC('+') AS [What]
	UNION ALL
	SELECT ISNUMERIC(CHAR(9)) AS [What]
	UNION ALL
	SELECT ISNUMERIC(CHAR(10)) AS [What]
	UNION ALL
	SELECT ISNUMERIC(CHAR(11)) AS [What]
	UNION ALL
	SELECT ISNUMERIC(CHAR(12)) AS [What]
	UNION ALL
	SELECT ISNUMERIC(CHAR(13)) AS [What]