DECLARE @A VARCHAR(128) = 'ABCDEF'
SELECT value FROM STRING_SPLIT(CAST(CAST(CAST(@A AS NVARCHAR) AS VARBINARY) AS VARCHAR), CHAR(0))

SET @A = 'Water,Coffee,Tea,Milk'

SELECT	Value
FROM	STRING_SPLIT(@A, ',')
