USE MYDATABASE -- CHANGE THE NAME OF THE DB
SET NOCOUNT ON
-- DROP FK TABLES NOT NEEDED IN DEVCUT
IF EXISTS (
		SELECT	1
		FROM	SYS.TABLES
		WHERE	NAME = 'FKCreate'
		)
	BEGIN
		TRUNCATE TABLE dbo.FKCreate
		DROP TABLE dbo.FKCreate
	END
GO

IF EXISTS (
		SELECT	1
		FROM	SYS.TABLES
		WHERE	NAME = 'FKDrop'
		)
	BEGIN
		TRUNCATE TABLE dbo.FKDrop
		DROP TABLE dbo.FKDrop
	END
GO