USE master;
GO
EXEC SYS.SP_MS_MARKSYSTEMOBJECT 'sp_DBA_GetPartitionedTables';
EXEC SYS.SP_MS_MARKSYSTEMOBJECT 'sp_DBA_CreateSwitchTable';
EXEC SYS.SP_MS_MARKSYSTEMOBJECT 'sp_DBA_SplitPartition';
EXEC SYS.SP_MS_MARKSYSTEMOBJECT 'sp_DBA_SwitchPartition';
EXEC SYS.SP_MS_MARKSYSTEMOBJECT 'sp_DBA_SwitchThenMergePartition';
